Make snprintf comply with -Werror=format-security
GENIVI/persistence-administrator pull request #5
Opened 2019-06-11 15:39 UTC by sashko

Fixes the following error when bulding with GCC 8.2 and
-Werror=format-security:

  error: format not a string literal and no format arguments
  [-Werror=format-security]

Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

2019-06-11 20:11 UTC, gunnarx requested changes

2019-06-11 20:11 UTC, gunnarx commented on Administrator/src/ssw_pers_admin_common.c
> +    snprintf(pchParentPath, "%s", sizeof(pchParentPath), compressFrom);
Good and important fix to make.  But when I looked at the details I got confused.

If snprintf has the following prototype:
```
int snprintf(char *str, size_t size, const char *format, ...);
```
then aren't these arguments in the wrong order?

Does it compile?

2019-06-17 21:24 UTC, sashko commented
@gunnarx

2019-06-18 13:15 UTC, gunnarx commented
Thanks @sashko.  OK, that looks correct.  Merging.

2019-06-18 13:15 UTC, merged